### ISSUE TITLE
Seems like Vanare version is more up2date than this forked repo

### ISSUE THREAD

**Issue by grEvenX** [cawolf/behat-cucumber-formatter#5]
What's the status of this project now that it seems Vanare has picked up maintaining the project?
If that's the preferred repo now perhaps it should be added in the Readme file. Tried the latest version of this fork and it errors when trying to run the behat test with the JSON formatter:
> Unrecognized option "filename" under "testwork.cucumber_json"

**Comment by cawolf** [comment]
Hi, sorry for the delay.

This plugin is actively used, albeit there are currently no code improvements. Therefore, it will coexist with the original repository for quite some more time.

Regarding your problem: that is why our use case made it necessary to work with file name prefixes instead of fixed file names. You can easily set `fileNamePrefix` instead of `filename`. See https://github.com/cawolf/behat-cucumber-formatter/blob/master/src/Extension.php#L40

**Comment by grEvenX** [comment]
Thank you for the update @cawolf , I missed the fact that there was changes to the configuration from the original. Changing it to use `fileNamePrefix` made it run as it should 👍 

For some reason the original repo hasn't been able to provide correct JSON files for me in the latest versions, while this one makes it work like it should with the Jenkins plugins.
